# Variables
BINARY_NAME=bin/mirroring
GEN_PATH=./edge/ebpf/
CMD_PATH=./cmd/mirroring

.PHONY: all
all: generate build

# Run go generate to compile BPF code and generate Go bindings
.PHONY: generate
generate:
	@echo "Running go generate..."
	go generate $(GEN_PATH)

# Build the user-space Go application
.PHONY: build
build:
	@echo "Building user-space binary..."
	mkdir -p bin
	go build -o bin/mirroring ./cmd/mirroring
	go build -o bin/collector ./cmd/collector

# Run the application (requires sudo for eBPF)
.PHONY: run
run: build
	@echo "Running interceptor (sudo)..."
	sudo $(BINARY_NAME)

# Clean up generated files and binaries
.PHONY: clean
clean:
	@echo "Cleaning artifacts..."
	rm -f bin/mirroring bin/collector
	# Remove files generated by bpf2go (assumes name patterns from gen.go)
	# Typically *_bpfeb.go, *_bpfel.go, and *.o files in the internal/ebpf directory
	find ./internal/ebpf -type f \( -name "*.o" -o -name "*_bpfel.go" -o -name "*_bpfeb.go" \) -delete

# Helper to verify eBPF capablities
.PHONY: verify
verify:
	@echo "Verifying environment..."
	@uname -r
	@bpftool --version || echo "bpftool not found"

# print kernel logs
.PHONY: logs
logs:
	@sudo cat /sys/kernel/debug/tracing/trace_pipe
# Dev Loop
.PHONY: cluster-up
cluster-up:
	@./scripts/dev-cluster.sh

.PHONY: cluster-down
cluster-down:
	@./scripts/teardown-cluster.sh

.PHONY: dev
dev:
	@~/.local/bin/tilt up
