apiVersion: v1
kind: Service
metadata:
  name: collector-service
spec:
  selector:
    app: collector
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: dev-registry:5000/collector:latest
        ports:
        - containerPort: 9000
