// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadKprobe returns the embedded CollectionSpec for Kprobe.
func LoadKprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Kprobe: %w", err)
	}

	return spec, err
}

// LoadKprobeObjects loads Kprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*KprobeObjects
//	*KprobePrograms
//	*KprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadKprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadKprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// KprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KprobeSpecs struct {
	KprobeProgramSpecs
	KprobeMapSpecs
	KprobeVariableSpecs
}

// KprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KprobeProgramSpecs struct {
	TraceSysClose *ebpf.ProgramSpec `ebpf:"trace_sys_close"`
	TraceSysWrite *ebpf.ProgramSpec `ebpf:"trace_sys_write"`
}

// KprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KprobeMapSpecs struct {
	ActiveConns *ebpf.MapSpec `ebpf:"active_conns"`
	Events      *ebpf.MapSpec `ebpf:"events"`
}

// KprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KprobeVariableSpecs struct {
}

// KprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type KprobeObjects struct {
	KprobePrograms
	KprobeMaps
	KprobeVariables
}

func (o *KprobeObjects) Close() error {
	return _KprobeClose(
		&o.KprobePrograms,
		&o.KprobeMaps,
	)
}

// KprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type KprobeMaps struct {
	ActiveConns *ebpf.Map `ebpf:"active_conns"`
	Events      *ebpf.Map `ebpf:"events"`
}

func (m *KprobeMaps) Close() error {
	return _KprobeClose(
		m.ActiveConns,
		m.Events,
	)
}

// KprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type KprobeVariables struct {
}

// KprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type KprobePrograms struct {
	TraceSysClose *ebpf.Program `ebpf:"trace_sys_close"`
	TraceSysWrite *ebpf.Program `ebpf:"trace_sys_write"`
}

func (p *KprobePrograms) Close() error {
	return _KprobeClose(
		p.TraceSysClose,
		p.TraceSysWrite,
	)
}

func _KprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kprobe_bpfel.o
var _KprobeBytes []byte
