// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type KprobeActiveReadArgs struct {
	_   structs.HostLayout
	Fd  uint32
	_   [4]byte
	Buf uint64
}

type KprobeConnState struct {
	_          structs.HostLayout
	LastSeenNs uint64
}

type KprobeHttpEvent struct {
	_         structs.HostLayout
	Pid       uint32
	Tgid      uint32
	Fd        uint32
	Len       uint32
	Direction uint8
	_         [7]byte
	Timestamp uint64
	Payload   [1024]int8
}

// LoadKprobe returns the embedded CollectionSpec for Kprobe.
func LoadKprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Kprobe: %w", err)
	}

	return spec, err
}

// LoadKprobeObjects loads Kprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*KprobeObjects
//	*KprobePrograms
//	*KprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadKprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadKprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// KprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KprobeSpecs struct {
	KprobeProgramSpecs
	KprobeMapSpecs
	KprobeVariableSpecs
}

// KprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KprobeProgramSpecs struct {
	TraceSysClose         *ebpf.ProgramSpec `ebpf:"trace_sys_close"`
	TraceSysEnterRead     *ebpf.ProgramSpec `ebpf:"trace_sys_enter_read"`
	TraceSysEnterRecvfrom *ebpf.ProgramSpec `ebpf:"trace_sys_enter_recvfrom"`
	TraceSysExitRead      *ebpf.ProgramSpec `ebpf:"trace_sys_exit_read"`
	TraceSysExitRecvfrom  *ebpf.ProgramSpec `ebpf:"trace_sys_exit_recvfrom"`
	TraceSysSendto        *ebpf.ProgramSpec `ebpf:"trace_sys_sendto"`
	TraceSysWrite         *ebpf.ProgramSpec `ebpf:"trace_sys_write"`
}

// KprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KprobeMapSpecs struct {
	ActiveConns *ebpf.MapSpec `ebpf:"active_conns"`
	ActiveReads *ebpf.MapSpec `ebpf:"active_reads"`
	Events      *ebpf.MapSpec `ebpf:"events"`
}

// KprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KprobeVariableSpecs struct {
}

// KprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type KprobeObjects struct {
	KprobePrograms
	KprobeMaps
	KprobeVariables
}

func (o *KprobeObjects) Close() error {
	return _KprobeClose(
		&o.KprobePrograms,
		&o.KprobeMaps,
	)
}

// KprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type KprobeMaps struct {
	ActiveConns *ebpf.Map `ebpf:"active_conns"`
	ActiveReads *ebpf.Map `ebpf:"active_reads"`
	Events      *ebpf.Map `ebpf:"events"`
}

func (m *KprobeMaps) Close() error {
	return _KprobeClose(
		m.ActiveConns,
		m.ActiveReads,
		m.Events,
	)
}

// KprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type KprobeVariables struct {
}

// KprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type KprobePrograms struct {
	TraceSysClose         *ebpf.Program `ebpf:"trace_sys_close"`
	TraceSysEnterRead     *ebpf.Program `ebpf:"trace_sys_enter_read"`
	TraceSysEnterRecvfrom *ebpf.Program `ebpf:"trace_sys_enter_recvfrom"`
	TraceSysExitRead      *ebpf.Program `ebpf:"trace_sys_exit_read"`
	TraceSysExitRecvfrom  *ebpf.Program `ebpf:"trace_sys_exit_recvfrom"`
	TraceSysSendto        *ebpf.Program `ebpf:"trace_sys_sendto"`
	TraceSysWrite         *ebpf.Program `ebpf:"trace_sys_write"`
}

func (p *KprobePrograms) Close() error {
	return _KprobeClose(
		p.TraceSysClose,
		p.TraceSysEnterRead,
		p.TraceSysEnterRecvfrom,
		p.TraceSysExitRead,
		p.TraceSysExitRecvfrom,
		p.TraceSysSendto,
		p.TraceSysWrite,
	)
}

func _KprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kprobe_bpfeb.o
var _KprobeBytes []byte
